{% set name = "mlconjug" %}
{% set version = "3.1.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a0ba92de0579ed0e74fc0d594bff3d4895728bd6e21b881f5c2b084c328cefbc" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 2
  entry_points:
    - mlconjug=mlconjug.cli:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - setuptools
    - pytest-runner
    - python
    - setuptools
  run:
    - python
    - cython
    - setuptools
    - click >=6.0
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - mlconjug

about:
  home: https://github.com/SekouD/mlconjug
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "[![pypi](https://img.shields.io/pypi/v/mlconjug.svg)](https://pypi.python.org/pypi/mlconjug)    [![travis](https://img.shields.io/travis/SekouD/mlconjug.svg)](https://travis-ci.org/SekouD/mlconjug)   [![appveyor](https://ci.appveyor.com/api/projects/status/6iatj101xxfehbo8/branch/master?svg=true)](https://ci.appveyor.com/project/SekouD/mlconjug) [![readthedocs](https://readthedocs.org/projects/mlconjug/badge/?version=latest)](https://mlconjug.readthedocs.io/en/latest/?badge=latest)  [![pyup](https://pyup.io/repos/github/SekouD/mlconjug/shield.svg)](https://pyup.io/repos/github/SekouD/mlconjug/)   [![codecov](https://codecov.io/gh/SekouD/mlconjug/branch/master/graph/badge.svg)](https://codecov.io/gh/SekouD/mlconjug)    [![snyk](https://snyk.io/test/github/SekouD/mlconjug/badge.svg?targetFile=requirements.txt)](https://snyk.io/test/github/SekouD/mlconjug?targetFile=requirements.txt)\n\n

A Python library to conjugate French, English, Spanish, Italian, Portuguese and Romanian verbs using Machine Learning techniques.\n\n


Any verb in one of the supported language can be conjugated, as the module contains a Machine Learning model of how the verbs behave.\n

Even completely new or made-up verbs can be successfully conjugated in this manner.\n\n


* Free software: MIT license\n
* Documentation: https://mlconjug.readthedocs.io.\n

Supported Languages\n
-------------------\n\n

- French\n
- English\n
- Spanish\n
- Italian\n
- Portuguese\n
- Romanian\n

\n\n"
  doc_url: https://mlconjug.readthedocs.io/en/latest/
  dev_url: https://github.com/SekouD/mlconjug

extra:
  recipe-maintainers:
    - SekouD
