{% set name = "mlconjug" %}
{% set version = "3.1.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a0ba92de0579ed0e74fc0d594bff3d4895728bd6e21b881f5c2b084c328cefbc" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - mlconjug=mlconjug.cli:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - setuptools
    - pytest-runner
    - python
    - setuptools
  run:
    - python
    - cython
    - setuptools
    - click >=6.0
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - mlconjug
  commands:
    - mlconjug --help

about:
  home: https://github.com/SekouD/mlconjug
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python library to conjugate French, English, Spanish, Italian, Portuguese and Romanian verbs using Machine Learning techniques.


Any verb in one of the supported language can be conjugated, as the module contains a Machine Learning model of how the verbs behave.

Even completely new or made-up verbs can be successfully conjugated in this manner.

The supplied pre-trained models are composed of:

- a binary feature extractor,
- a feature selector using Linear Support Vector Classification,
- a classifier using Stochastic Gradient Descent.

MLConjug uses scikit-learn to implement the Machine Learning algorithms.

Users of the library can use any compatible classifiers from scikit-learn to modify and retrain the models.

The training data for the french model is based on Verbiste https://perso.b2b2c.ca/~sarrazip/dev/verbiste.html .

The training data for English, Spanish, Italian, Portuguese and Romanian was generated using unsupervised learning techniques
  using the French model as a model to query during the training.


* Free software: MIT license
* Documentation: https://mlconjug.readthedocs.io.

Supported Languages
-------------------

- French
- English
- Spanish
- Italian
- Portuguese
- Romanian


Features
--------

- Easy to use API.
- Includes pre-trained models with 99% + accuracy in predicting conjugation class of unknown verbs.
- Easily train new models or add new languages.
- Easily integrate MLConjug in your own projects.
- Can be used as a command line tool.

Credits
---------

This package was created with the help of [Verbiste](https://perso.b2b2c.ca/~sarrazip/dev/verbiste.html) and [scikit-learn](http://scikit-learn.org/stable/index.html).

The logo was designed by [Zuur](https://github.com/zuuritaly).


\n\n"
  doc_url: https://mlconjug.readthedocs.io/en/latest/
  dev_url: https://github.com/SekouD/mlconjug

extra:
  recipe-maintainers:
    - SekouD
