travis:
  secure:
    BINSTAR_TOKEN: RlneC8o22IkODkVhTi6cjPEWju+TjBh4bAbhv3VYm3EvNVNxkDv53DG50NebU+CnrY1/D+x3aT+O+nzm/LFOar5Ljy2cd6Uj/FF4+cbIxvci2eNugEZwGsWs3sA4iDKRtBaEWjm/yh7Pm2ml2lwPif913bSNA9xn6JvnT331FpFIQp1MMNTYudzSUQs/a3Emtt+vSeWvVYQc1QGFHrG4iBpUKQYwb7sKEVHKrJTOB3+QSr+GkPI7l1wQmP4dxy1Fqr3qxuYKSQ4cLSHGkMhJXpuPhtqmvEGgc68gH1KA5wDPz0bWKhdiTXZ6AAltKWz9A+48EzGNFMm5ecqXTm/UNCj5sFUEWyipWvbaj1iKYrRtyirVoKClM3fpnW7y1azYWv2v5uXvavk35BHsGVFHdQLuSUQvWfslHHe2yhhIKCY6KH4STAxCCeqviIapJYWC3EaTEpAvoStOYV6mwHzE4bVo4dQHT1BIaSMPb7DkszXKyNlhqEqwcvPb5d5TVys40YKePKsNg+wAuPY4XrFUktWzswrJawX0i+56OY4dOHNcK5dzU1qJPn+DHjBHj0Kmz/cPZe/rL92xSLhVh1GnXrzt1+w6YHHybFRhHZuRWYa8tf0swn6tPbuvQhEkCOENqcIH671QZLEvYSkfvPaRctrjgEWkFrnxdx5OgJIleQM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
